### ISSUE TITLE
A library should not use its dependecies from source

### ISSUE THREAD

**Issue by dimztimz** [alandefreitas/matplotplusplus#11]
Instead, it should strictly use `find_package` or maybe `find_library`. There shouldn't be CPM.cmake, no Hunter, no `FetchContent` + `add_subdirectory`. Those things are useful only for executables. If you are bundling the dependencies, you can easily get ODR violations. Additionally you make the library harder for packaging in other package managers like apt or vcpkg. For example

```
My Prog ---- depends -----> matplot++ ----- depends ------> bundled/downloaded glfw
          \
           -----------------------------------------------> system glfw
```

And now you have a ODR violation because you have 2 glfw in the program. See this CppCon talk for more info https://www.youtube.com/watch?v=sBP17HQAQjk

As a middle ground, you should always use `find_package` for popular libraries and use CPM for stuff that isn't available in other package managers.

**Comment by alandefreitas** [comment]
You're absolutely right. I'll try to come up with a FindGLFW.cmake and FindGLAD.cmake to solve this.

**Comment by dimztimz** [comment]
For glfw you don't need FindGLFW.cmake, it provides all the necessary files (glfw3Config.cmake and others). You need only this

```cmake
find_package(glfw3) # notice the 3
target_link_libraries(.... glfw) # no 3 here
```

I don't know for the others.

**Comment by alandefreitas** [comment]
That's great. For GLFW3, it would probably require some extra code to make sure CMAKE_MODULE_PATH has access to glfw3Config.cmake or FindGlfw3.cmake. Otherwise, users would get

```
By not providing "Findglfw3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glfw3", but
  CMake did not find one.
```

But that's not complicated though. I'll have a look at that. 

GLFW3 and GLAD are just dependencies for the example of what an OpenGL backend could look like. In the future, this should probably move to another repository anyway.

**Comment by alandefreitas** [comment]
That should solve it
https://github.com/alandefreitas/matplotplusplus/commit/92bd21ec56cf27ec8d389121a878f1a90cff0a8d

**Comment by dimztimz** [comment]
You should fix other dependencies too like cimg and nodesoup.

CImg is popular library already shipped in Linux distributions. For cimg, find_pacakge() can't work. You can use something like `find_path` to search if the header `CImg.h` exists.

**Comment by alandefreitas** [comment]
I had no idea shipped in Linux distributions. That's certainly not the case for windows and mac os. Some people were suggesting I embedded CImg and nodesoup into the library because they are header-only (cimg) or just a couple of files (nodesoup). That is kind of the opposite route for cimg though.

**Comment by lacc97** [comment]
You could look for the system dependencies and provide a fallback to
bundled versions of the dependencies.

Maybe define some CMake option to control this (i.e. pass
`-DWITH_SYSTEM_CIMG=ON -DWITH_SYSTEM_NODESOUP=ON` or something along those
lines).
