### ISSUE TITLE
Error compiling with NVCC

### ISSUE THREAD

**Issue by kaffehalv** [alandefreitas/matplotplusplus#111]
I am trying to use Matplot++ in a project heavily dependent on CUDA, so I am compiling with NVCC. And I get this error.

`_deps/matplot-src/source/matplot/core/axes_type.h:2790:38: error: ‘colormap_palette’ has not been declared
 2790 |         std::vector<std::vector<double>> colormap_{palette::default_map()};
`
The code is fine. It is NVCC that is erroneous. But a simple fix is to initialize the `colormap_` using

 `std::vector<std::vector<double>> colormap_ = {palette::default_map()};`

**Bug catergory** - compilation error
**Platform** - Linux

Environment Details:

- OS: Manjaro Linux
- Compiler: NVCC v11.1.105 (g++ v10.2.0 for host code)

**Comment by alandefreitas** [comment]
I see. I'll have a better look at it in the next days.

Or feel free to open a small PR with that change.

**Comment by kaffehalv** [comment]
I made a PR. This is my first time contributing to someon else's repo, so I hope I did everything correct.
