### ISSUE TITLE
CMake minimum version

### ISSUE THREAD

**Issue by jube** [alandefreitas/matplotplusplus#173]
**Bug category**

- [ ] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [ ] *bug - runtime warning*
- [ ] *bug - logic error*

It's a configure error.

**Describe the bug**

`Matplot++Config.cmake.in` uses `list(POP_BACK ...)` cmake command that appeared in CMake 3.15 but the minimum required version is 3.14. It should be updated to 3.15.

**Comment by alandefreitas** [comment]
[Done](https://github.com/alandefreitas/matplotplusplus/commit/26cfa754457eecb815689dec53b4d8a409152a3a)!

Thanks for noticing.
