### ISSUE TITLE
Warnings and compilation errors when compiling `util/common.cpp`

### ISSUE THREAD

**Issue by teonnik** [alandefreitas/matplotplusplus#18]
OS: Linux 5.7.12-arch1-1 (Arch Linux) 
Compiler: gcc 10.1.0
CMake 3.18.1

[Error log](https://pastebin.pl/view/97bd935f)
[CMake setup](https://pastebin.pl/view/9b219306)

**Comment by alandefreitas** [comment]
Try removing:

```cmake
pkg_check_modules(MAGICK Magick++)
if(MAGICK_FOUND)
    message("MAGICK Found")
    target_compile_definitions(cimg INTERFACE cimg_use_magick)
    target_link_libraries(cimg INTERFACE ${MAGICK_LIBRARIES})
    target_include_directories(cimg INTERFACE ${MAGICK_INCLUDE_DIRS})
endif()
```

from [FindDependencies.cmake](https://github.com/alandefreitas/matplotplusplus/blob/3781773832306e5571376f29f0c1d1389eb82af0/source/matplot/FindDependencies.cmake#L95)

Does that solve the problem?

**Comment by teonnik** [comment]
Yes, it does. Everything compiles.
