### ISSUE TITLE
Subplots disappear when window size is changed

### ISSUE THREAD

**Issue by b4sgren** [alandefreitas/matplotplusplus#198]
I can create a figure with subplots but when I change the size of the window (maximize to fill the screen) all the subplots disappear except the last one. The issue can be recreated by running any of the examples in examples/appearance/multiplot/subplot (I did it with example 11 and 6).

Nothing that I have tried can get the other subplots to reappear after the window size has been changed.

Here is the example before I make the window full screen.
![subplots jpg](https://user-images.githubusercontent.com/39415319/137375621-f7e6dcf0-908b-4872-864b-0955a972625c.png)

here is after I make the window full screen.
![fullscreen_subplots jpg](https://user-images.githubusercontent.com/39415319/137375709-7a53e30e-d595-43bb-a42a-c765b0ba0080.png)

I'm running this on Ubuntu 20.04

**Comment by alandefreitas** [comment]
Yes. It seems like gnuplot only replots the last plot when resizing the window. There's no way to ask gnuplot to redraw the plots when the window is resized either, because the pipe is unidirectional.

One thing you can do is set the window size programmatically before you create the plot.

**Comment by b4sgren** [comment]
Ok, I haven't tried using a different backend yet but could this potentially be fixed by uisng OpenGL or one of the other experimental backends?

**Comment by hoppss** [comment]
How do replot the last plot when resizing the window ? 

Just not to resize the window and pre-define the window size ?
