### ISSUE TITLE
Version 1.1.0

### ISSUE THREAD

**Issue by Riley16** [alandefreitas/matplotplusplus#205]
### Discussed in https://github.com/alandefreitas/matplotplusplus/discussions/150

<div type='discussions-op-text'>

<sup>Originally posted by **alandefreitas** May 20, 2021</sup>
- New vector fields plot with colormap magnitudes (Thanks @matthew-hennefarth)
- Support for experimental filesystem
- All pedantic warnings fixed for MSVC, GCC, and Clang
- Improved tests and CI workflows

<hr /><em>This discussion was created from the release <a href='https://github.com/alandefreitas/matplotplusplus/releases/tag/v1.1.0'>Version 1.1.0</a>.</em></div>

**Comment by Riley16** [comment]
I seem to be unable to unzip the Linux binary packages via gunzip, getting the following error on Ubuntu 20.04.2 LTS (WSL 2) with latest version of tar:

'''tar -xvzf matplotplusplus-1.1.0-Linux.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now'''

What version of tar were these archives created with? I've had no recent issues decompressing tar files otherwise.

**Comment by alandefreitas** [comment]
It relies on this Github action: https://github.com/alandefreitas/matplotplusplus/blob/41a42e7925a3214d865947bcd32e4dd7df3a3ab6/.github/workflows/build.yml#L106

I never had any problem unzipping these files but I just noticed 1) this file should just contain all the other linux artifacts, 2) these artifacts have names such as Matplot++-1.1.0-Linux.sh and 3) the action is using the template `matplotplusplus-?.?.?-*.*` which is not matching the artifacts anymore so the zip file is empty. 

The action parameters should have been updated when the name of the config file was updated.

**Comment by Riley16** [comment]
Okay, yeah I should have mentioned that I was trying to use curl <download_URL to download the file, which probably led to incorrect results from those Github actions being stored as the output file. I had no issues just downloading the archive directly from my browser and then de-tarring. Thanks!
