### ISSUE TITLE
Adding release tags

### ISSUE THREAD

**Issue by ethren** [alandefreitas/matplotplusplus#24]
Hello,
I would like to thank you for this amazing library, it is wonderful!

I am really interested in getting notifications about the releases of this library. I could select `Watch` to get all the notifications (issues, etc.). However, because currently there are no release tag and there are a lot of notifications, could you please add release tags to the library so one could choose to get notifications about releases only?

I appreciate your work
My best regards

**Comment by alandefreitas** [comment]
Hi,
I was waiting until the library seemed to be working to everyone to create a v0.1 or something. 
That way, anyone could use the tag to download something more stable while we improve the library.
I'll have a look at that.

**Comment by alandefreitas** [comment]
Done: https://github.com/alandefreitas/matplotplusplus/releases/tag/v1.0
😀
