### ISSUE TITLE
'imagesc' support colormap like Matlab

### ISSUE THREAD

**Issue by diverger** [alandefreitas/matplotplusplus#266]
It seems the 'imagesc' function won't support colormap.

**Comment by alandefreitas** [comment]
This?

https://alandefreitas.github.io/matplotplusplus/plot-types/images/image-matrix/

**Comment by diverger** [comment]
This

https://alandefreitas.github.io/matplotplusplus/plot-types/images/scaled-image/

**Comment by diverger** [comment]
I tried this

https://alandefreitas.github.io/matplotplusplus/plot-types/images/scaled-image/

And it works.
