### ISSUE TITLE
[compilation error] 'localtime_s' was not declared in this scope

### ISSUE THREAD

**Issue by erusyd** [alandefreitas/matplotplusplus#282]
**Bug category**

- [x] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [ ] *bug - runtime warning*
- [ ] *bug - logic error*

**Describe the bug**
Compile from the source, it complains:
error: ‘localtime_s’ was not declared in this scope

**Steps to Reproduce**

```bash
# Your steps go here
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O2" -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF 
sudo cmake --build . --parallel 2 --config Release
sudo cmake --install .
```

**Output**
/source/matplot/core/axis_type.cpp:260:21: error: ‘localtime_s’ was not declared in this scope; did you mean ‘localtime_r’?
260 |                     localtime_s(&buf, &now);
      |                     ^~~~~~~~~~~
      |                     localtime_r
make[2]: *** [source/matplot/CMakeFiles/matplot.dir/build.make:128: source/matplot/CMakeFiles/matplot.dir/core/axis_type.cpp.o] Error 1
<details>
 
```console
# The output you got
```
</details>

**Platform**

- [x] *cross-platform issue - linux*
- [ ] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*

**Environment Details:**
 - OS: linux mint
 - OS Version: 20.3
 - Compiler: g++
 - Compiler version: 9.4.0

**Additional context**

**Comment by IasonManolas** [comment]
I face the same issue under Ubuntu 20.04 while compiling with clang 12

**Comment by TheGreatRambler** [comment]
Ah hmm this is my fault, sorry guys. A PR adding support for timestamps I added was merged with this bug

**Comment by TheGreatRambler** [comment]
Msvc actually errors, not warns, when you use `localtime` so I mistakenly believed I missed something...

**Comment by mangoschorle** [comment]
Same here
OS: linux ubuntu
OS Version: 22.04
Compiler: g++
Compiler version: 9.4.0

**Comment by Menzoc** [comment]
Hello Fellows,

I had the same issue. There is two localtime_s, one from[Windows Visual Studio](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?redirectedfrom=MSDN&view=msvc-170)  extension and one from [C standard library](https://en.cppreference.com/w/c/chrono/localtime).

 My compiler clearly understood that we are using Window ones so it doesn't compile.

For the time being I came back to a previous versions by the following command `git reset --hard 8dbea7 `
I didn't find yet the way to change from Window.

To be honest, I'm a bit disappointed to see two function with the exact same name not compatible. However, it is clearly state in the description of the C Library:

> The implementation of localtime_s in [Microsoft CRT](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=vs-2019) is incompatible with the C standard since it has reversed parameter order and returns errno_t.
