### ISSUE TITLE
CMake options missing project specific prefix

### ISSUE THREAD

**Issue by globberwops** [alandefreitas/matplotplusplus#315]
**Feature category**
- [ ] *enhancement - backends*
- [x] *enhancement - build system*
- [ ] *enhancement - documentation*
- [ ] *enhancement - plot categories*

**The problem**

CMake options do not have a project specific prefix and may hence interact/interfere with the cache variables of a parent project.

**The solution I'd like**
Prefix CMake options with the project name.
This will not only fix the above problem, but will also nicely cluster the variables in the CMake cache and the CMake GUI.

**Alternatives I've considered**
None.

**Comment by alandefreitas** [comment]
Yes. Namespacing these options would be great. It has caused me a few problems in past as well.
