### ISSUE TITLE
Ubunto error with gcc 8++:  error: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by paklau99988** [alandefreitas/matplotplusplus#33]
Is get error:

```
[  2%] Building CXX object source/matplot/CMakeFiles/matplot.dir/util/common.cpp.o
In file included from /usr/include/OpenEXR/ImfHeader.h:51,
                 from /usr/include/OpenEXR/ImfRgbaFile.h:50,
                 from matplotplusplus/source/3rd_party/cimg/CImg.h:549,
                 from matplotplusplus/source/matplot/util/common.cpp:16:
/usr/include/OpenEXR/ImathVec.h:228:34: error: ISO C++17 does not allow dynamic exception specifications
     const Vec2 & normalizeExc () throw (IEX_NAMESPACE::MathExc);

```

Same as here: https://github.com/stack-of-tasks/pinocchio/issues/786

**Comment by nspo** [comment]
As mentioned in the other issue, it seems this library (OpenEXR) in the state in the repos of Ubuntu 18.04 is not compatible with C++17.

**Comment by nspo** [comment]
@alandefreitas Yes, it does on Ubuntu 18.04. It compiles successfully and the examples I tried run afterwards!

If you'd like to support Ubuntu 18.04 it should be mentioned that the default Cmake version is 3.10, i.e. lower than the specified minimum. One can of course install a newer cmake manually though (which I for example did.

**Comment by alandefreitas** [comment]
So I'm removing this dependency since (i) it's optional, and (ii) it's not compatible with C++17
https://github.com/alandefreitas/matplotplusplus/commit/4d19af6f964f4e8cf100da6ca62fcb8d9699283e
