### ISSUE TITLE
Cimg linker error

### ISSUE THREAD

**Issue by kurogane1031** [alandefreitas/matplotplusplus#35]
**Describe the bug**
Unable to compile due to linker error.

**Steps to Reproduce**
1. Matplot++ folder is seperated from my code (no using add subdirectory)
2. make && make install matplot++ package.
3. Attempt to use matplot++ package on my code.

**Output**
```
/usr/bin/ld: cannot find -lcimg
```

**Environment:**
 - OS: 18.04
 - Compiler: g++ and clang++
 - Compiler version: 10

**Additional context**
Currently I am able to both `make` and `make install` matplot++. However, when I tried using it on my code, I got linking error regarding cimg. Previous I am able to compile my code by just having the following in my `CMakeLists.txt`. 
```
find_package(Matplot++)
find_package(Filesystem) 

add_executable(run main.cpp)
target_link_libraries(run PUBLIC Matplot++::matplot)
```

However, if I'm using similar CMakeLists.txt now, I'm having linker error of `cimg`. I think it might be related with [this](https://github.com/alandefreitas/matplotplusplus/commit/44e186e9e6916800d930f7b73a85d73223820cce). Thus, if possible, I would like to ask what else do I need to add in my CMakeLists.txt in order to not having this error.

**Comment by alandefreitas** [comment]
@lacc97 Maybe `WITH_SYSTEM_CIMG` was not considered in https://github.com/alandefreitas/matplotplusplus/pull/25 ?
I'm not sure.

**Comment by lacc97** [comment]
Which CMake configuration options are you using?

**Comment by lacc97** [comment]
There's a PR (#36) that should hopefully fix this issue.

Also, it shouldn't be necessary for you to add `find_package(Filesystem)`, just `find_package(Matplot++)` should be enough now.
