### ISSUE TITLE
Plot not showing up - exit with error code 3

### ISSUE THREAD

**Issue by psykovski-extended** [alandefreitas/matplotplusplus#381]
**Bug category**

- [ ] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ x] *bug - runtime error*
- [ ] *bug - runtime warning*
- [ ] *bug - logic error*

**Describe the bug**

The issue I am facing seems kinda strange:
The program compiles and links without any problems or warnings showing up in the console. But when I run the `.exe` file, there are no plots showing up - it just terminates with return value 3.
I installed the code with cloning it into my projects directory and added it in the cmake file with `add_subdirectory`.
OS: Windows 10 Home
Compiler: gcc (11.2.0), g++ (11.2.0) (installed with Mingw)
gnuplot version (gnuplot 5.4 patchlevel 8)

I also tried debugging it, but the program exits before it can even hit the first breakpoint...

Any suggestions for this? Thanks in advance!

**Platform**

- [ ] *cross-platform issue - linux*
- [ ] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*

**Comment by psykovski-extended** [comment]
I now was able to debug and to get a little bit more information on about what is going wrong:
In the file `common.cpp` on line 56, `pipe` holds the value `empty`, therefore throwing an runtime error.

I checked if I am able to run this command `gnuplot -e "set terminal wxt" 2>&1` on the command line - and it runs, but doesn't give any output. What would be the supposed output be on the command line? Is version 5.4.8 of gnuplot not supported by this library?

**Comment by psykovski-extended** [comment]
As usual - go away from it for a week, come back to it and BAM! it works... I have changed nothing since the last time, but it seems like that it just decided to work - so sorry for interrupting real and serious issues, this one is now closed!

**Comment by iamjadhav** [comment]
@psykovski-extended 

I'm facing the same issue with VS 19.
Did it actually just went away?
Could it have been because of a change in the git repo as you added Matplot as a subdirectory with FetchContent?

![image](https://github.com/alandefreitas/matplotplusplus/assets/35925489/b182534a-225d-4dec-81c8-886b43fd2730)

**Comment by psykovski-extended** [comment]
Are you able to call `gnuplot` from the command line? And I was using GCC, you are using Visual C++, maybe that's a problem?

**Comment by iamjadhav** [comment]
Yes, that was the problem.
Stupidly enough, I did not have `gnuplot`. Installing it solved the issue.
Thanks!
