### ISSUE TITLE
visualization for ML/DS

### ISSUE THREAD

**Issue by leannejdong** [alandefreitas/matplotplusplus#39]
Would that be feasible to add heat map and saliency map to this repo?

**Comment by alandefreitas** [comment]
You can you `heatmap` for heatmaps and `imagesc` for saliency maps.
Some examples:
* https://github.com/alandefreitas/matplotplusplus/tree/master/examples/data_distribution/heatmap
* https://github.com/alandefreitas/matplotplusplus/tree/master/examples/images/imagesc
* https://github.com/alandefreitas/matplotplusplus#heatmap
* https://github.com/alandefreitas/matplotplusplus#scaled-image
