### ISSUE TITLE
call to legend(...) function causes the figure to go blank

### ISSUE THREAD

**Issue by swacisko** [alandefreitas/matplotplusplus#44]
**Bug category**
- [x] *bug - runtime error*

**Describe the bug**
I was trying to run the script: 

    using namespace matplot;
    auto rdm = rand(4, 4, 0, 1);
    plot(rdm);
    auto lgd = legend("Line 1", "Line 2", "Line 3", "Line 4");
    lgd->font_size(12);
    lgd->text_color("blue");
    lgd->num_columns(2);
    wait();

This is the content of the legend_8.cpp file (with show() replaced by wait() - when i try to use show() i get an error "error: ‘show’ was not declared in this scope").

The plot() function works OK - the plot is shown and I can see it (after pausing before calling legend() ), but the legend() function causes the whole figure to go blank.
The figure goes blank after fflush(pipe_); in matplotplusplus/source/matplot/backend/gnuplot.cpp:

```
bool gnuplot::flush_commands() {
        if constexpr (dont_let_it_close_too_fast) {
            last_flush_ = std::chrono::high_resolution_clock::now();
        }
        fputs("\n", pipe_);
        fflush(pipe_);
        if constexpr (trace_commands) {
            std::cout << "\n\n\n\n" << std::endl;
        }
        return true;
    }
```

Each of the lines
    auto lgd = legend("Line 1", "Line 2", "Line 3", "Line 4");
    lgd->font_size(12);
    lgd->text_color("blue");
    lgd->num_columns(2);
results in a "line X: undefined variable: keyentry" error log.

The buffer before flushing seems to contain the following data:
"reset\nset terminal qt title \"Figure 1\"\nset terminal qt title \"Figure 1\" size 560,420 enhanced font \"Helvetica,10\"\nset multiplot\nset object 1 rectangle from screen 0,0 to screen 1,1 behind fillcolor rgb \"0x00EFEFEF\" fillstyle solid 1.0 noborder\n    # Axes position\n    set origin 0.130000,0.110000\n    set size 0.775,0.815\n    set lmargin at screen 0.13\n    set rmargin at screen 0.905\n    set bmargin at screen 0.11\n    set tmargin at screen 0.925\n    # Axes title\n    unset title\n    # Axes box\n    set border 15 linecolor \"black\" linewidth 0.5\n    set format x \"%g\"\n    set xtics textcolor \"0x00262626\" font \"Helvetica,10\" nomirror in scale 0.75 \n    unset xzeroaxis\n    unset x2tics\n    unset x2zeroaxis\n    set format y \"%g\"\n    set ytics textcolor \"0x00262626\" font \"Helvetica,10\" nomirror in scale 0.75 \n    unset yzeroaxis\n    unset y2tics\n    unset y2zeroaxis\n    unset colorbox\n    # Axes ranges\n    set xrange [:] noreverse\n    set yrange [:] noreverse\n    set y2range [:] noreverse\n    # Axes scale\n    # Axes labels\n    # Axes legend\n    set key on font \"Helvetica,11\" textcolor rgb 'black' inside right top vertical Left opaque reverse noinvert width 1 noautotitle box linecolor rgb \"black\" dashtype 1 linewidth 0.5 linetype -1\n    # Axes background\n    set object 2 rectangle from graph 0,0 to graph 1,1 behind fillcolor rgb \"white\" fillstyle solid 1.0 noborder\n    # Axes objects\n    \n    plot  '-'  with line linecolor rgb \"0x000071BC\" dashtype 1 linewidth 0.5 linetype -1,\\\n          '-'  with line linecolor rgb \"0x00D85218\" dashtype 1 linewidth 0.5 linetype -1,\\\n          '-'  with line linecolor rgb \"0x00ECB01F\" dashtype 1 linewidth 0.5 linetype -1,\\\n          '-'  with line linecolor rgb \"0x007D2E8D\" dashtype 1 linewidth 0.5 linetype -1,  keyentry  with line linecolor rgb \"0x000071BC\" dashtype 1 linewidth 0.5 linetype -1 title \"Line 1\",  keyentry  with line linecolor rgb \"0x00D85218\" dashtype 1 linewidth 0.5 linetype -1 title \"Line 2\",  keyentry  with line linecolor rgb \"0x00ECB01F\" dashtype 1 linewidth 0.5 linetype -1 title \"Line 3\",  keyentry  with line linecolor rgb \"0x007D2E8D\" dashtype 1 linewidth 0.5 linetype -1 title \"Line 4\"\n        1  0.571241  \n    2  0.726632  \n    3  0.906632  \n    4  0.720572  \n    e\n\n        1  0.312834  \n    2  0.689955  \n    3  0.587253  \n    4  0.464875  \n    e\n\n        1  0.280091  \n    2  0.280318  \n    3  0.637555  \n    4  0.156573  \n    e\n\n        1  0.125977  \n    2  0.992371  \n    3  0.916899  \n    4  0.733797  \n    e\n\n    \nunset object 1\nunset multiplot\n"

**Output**

<details>
 
```console
qt5ct: using qt5ct plugin
           line 46: undefined variable: keyentry

           line 69: undefined variable: keyentry

           line 92: undefined variable: keyentry

           line 115: undefined variable: keyentry
```
</details>

**Platform**
- [ ] *cross-platform issue - linux*

Linux 4.15.0-64-generic x86_64
NAME="Linux Mint"
VERSION="19 (Tara)"

**Comment by alandefreitas** [comment]
The example works fine here with both `show` and `wait`. 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/5369819/92308101-bd084480-ef71-11ea-8ca4-4b50657870a3.png">

Problem 1) show/wait

The only reason to replace `wait` there is that (i) some platforms already have `wait` defined in the global namespace and (ii) `show` is the generic function for any backend while `wait` is wait the Gnuplot `show` function does. 

`show` is defined right the in [plot.h](https://github.com/alandefreitas/matplotplusplus/blob/9287d128e4e3ed87fc316cdb0b6847b0e0444f56/source/matplot/freestanding/plot.h#L966). And it's included [directly in `matplot.h`](https://github.com/alandefreitas/matplotplusplus/blob/9287d128e4e3ed87fc316cdb0b6847b0e0444f56/source/matplot/matplot.h#L49). 

I don't see a reason why `show` wouldn't work in a given platform yet. Can you check if these includes are ok over there?

Problem 2) keyentry

You can always paste the output in gnuplot and check if it works, but it seems like gnuplots does not have the `keyentry` command yet. [Keyentry](http://gnuplot.sourceforge.net/demo_svg_5.5/custom_key.html) has been around [for 2 years](https://github.com/gnuplot/gnuplot/blob/6753adf04b4da306ec030ba078fe044cf3b64a25/demo/keyentry.dem) now but some platforms haven't upgraded yet. You need your gnuplot version to be [higher than 5.2.6](http://gnuplot.info/ReleaseNotes_5_2_6.html).

**Comment by alandefreitas** [comment]
This might help a little: a898a2555512eace8d016608ba5ce094832b31e4

**Comment by swacisko** [comment]
Thanks a lot!
It occurs that I had no show() function in my plot.h file. I downloaded current version and also upgraded gnuplot from 5.2.2 to 5.2.7 and everything is perfect now.
Thank you once again for your help and the whole project - it is really awesome!
