### ISSUE TITLE
Include directives are missing throughout the whole code base

### ISSUE THREAD

**Issue by globberwops** [alandefreitas/matplotplusplus#5]
Throughout the whole code base there are include directives missing e.g.

- source/matplot/core/axes.h
  `#include <array>`
  `#include <memory>`
- source/matplot/core/axes_object.h
  `#include <memory>`
- source/matplot/core/line_spec.h
  `#include <functional>`
- source/matplot/util/colors.h
  `#include <vector>`

CMake and [include-what-you-use](https://include-what-you-use.org/) can be of help here, see [CMAKE_CXX_INCLUDE_WHAT_YOU_USE](https://cmake.org/cmake/help/latest/prop_tgt/LANG_INCLUDE_WHAT_YOU_USE.html)

**Comment by cguebert** [comment]
To compile with MSVC, I also added:
- source/matplot/axes_object/network.cpp
- source/matplot/axes_object/parallel_lines.cpp
- source/matplot/core/axes.cpp
`#include <iomanip>`
- source/matplot/axes_object/surface.h
`#include <optional>`
- source/matplot/util/common.h
`#include <functional>`
- source/matplot/util/contourc.cpp
`#include <cassert>`
- source/matplot/util/geodata.h
`#include <string>`
- source/matplot/util/handle_types.h
`#include <memory>`
- source/matplot/util/type_traits.h
`#include <vector>`

**Comment by huand** [comment]
extract of error i get when compiling an plot3 example:
https://pastebin.com/k0F8SfW9

**Comment by mrexodia** [comment]
I think this can be closed now
