### ISSUE TITLE
Typos in "Installing" Documentation

### ISSUE THREAD

**Issue by jusevitch** [alandefreitas/matplotplusplus#53]
The 5 lines for installation from the "Installing" section in README.md didn't run for me as written (using CMake 3.16.3 on Ubuntu 20.04). There seems to be the following typos in these lines:

* In line 3, `-BUILD_TESTS=OFF` is missing a D. I think it should be `-DBUILD_TESTS=OFF`.
* In line 5, I think `cmake --install` should be `cmake --install .` with a period at the end.

In addition, I had to add the option `-DBUILD_SHARED_LIBS=ON` to line 3 and append `/usr/local/lib/` to `LD_LIBRARY_PATH` for my custom C++ executables to run correctly when importing and using Matplot++.

This probably isn't a big deal for more experienced CMake users, but it took me a little while to figure out why my custom C++ executables using Matplot++ weren't compiling / running.

Thanks for creating this library! Looking forward to using it.

**Comment by alandefreitas** [comment]
Hey, @jusevitch. Thank you for pointing these typos. It would take me a while to notice that because I rarely do any of that manually.

I've just changed the README.md and next week we should have packages for people who don't want to worry about any of that. I hope the library helps you.
