### ISSUE TITLE
Subplots crashing into each other

### ISSUE THREAD

**Issue by multiplemonomials** [alandefreitas/matplotplusplus#54]
Sorry if this is a noob question, but I made a graph with three subplots and they are visually colliding with each other:
![image](https://user-images.githubusercontent.com/2099358/92980305-766f8a00-f44a-11ea-9a1d-8da11029fdab.png)
Any idea how to fix this? Using gnuplot backend on Windows.  Thanks!

**Comment by alandefreitas** [comment]
Subplots don't always make room for all kinds of labels. You can change the axes' position and size to make them smaller though. In your case, adjusting the height must be enough:

```cpp
auto ax = gca();
ax->height(ax->height() * 0.5);
```

You probably also need a larger figure there.
