### ISSUE TITLE
Unable to hide the colorbar

### ISSUE THREAD

**Issue by hiddefolkertsma** [alandefreitas/matplotplusplus#63]
Hi,

First of all, thanks for creating this library :slightly_smiling_face:. I have a question about hiding a colorbar in a 3D scatterplot (but this may apply to other types of plots as well). When I set the axes visibility to `false`, a colorbar appears. I can't seem to hide it, despite calling the appropriate functions for doing so. This only happens when passing color labels to `scatter3`.

I'm not sure if this is a bug. If not, how can I hide the colorbar?
Full working example below (adapted from `example_scatter3_5`):
```c++
#include <matplot/matplot.h>
#include <random>
#include <tuple>

int main() {
    using namespace matplot;

    auto z = linspace(0, 4 * pi, 250);
    auto x = transform(z, [](double z) { return 2 * cos(z) + rand(0, 1); });
    auto y = transform(z, [](double z) { return 2 * sin(z) + rand(0, 1); });

    std::vector<double> sizes(x.size(), 5);
    std::vector<double> colors(x.size() / 2, 1);
    std::fill_n(std::back_inserter(colors), x.size() / 2, 2);

    scatter3(x, y, z, sizes, colors, "filled");
    colormap(palette::paired());

    auto ax1 = gca();

    // Hide the x, y, z axes. This causes a colorbar to appear.
    // The colorbar only appears when colors is passed to scatter3
    ax1->visible(false);

    colorbar(off); // Doesn't work
    colorbar().visible(false); // Doesn't work either

    view(-30, 10);

    show();
    return 0;
}
```
![colorbar](https://user-images.githubusercontent.com/14166902/93716707-a23cef00-fb71-11ea-8fe5-c90879592885.png)

**Comment by alandefreitas** [comment]
Interesting. That must be a logic error. I'll try to replicate the problem and see what's happening there.

In the meanwhile, if the colors are discrete, you can try two scatter plots. 

Or maybe you can try to hide the individual axis objects:

```cpp
ax1->x_axis()->visible(false);
// ...
```

instead of 

```cpp
ax1->visible(false);
```

I haven't tested that, but it might be worth trying.

**Comment by hiddefolkertsma** [comment]
Thanks for the quick reply! Just tested hiding the individual axis objects; same result.

**Comment by alandefreitas** [comment]
OK. While I don't fix this, you can also set this to true or set TRACE_GNUPLOT_COMMANDS to get the gnuplot commands generated for your image:
https://github.com/alandefreitas/matplotplusplus/blob/4eb18ab9b7650542ff001179c93138c7f0793a5e/source/matplot/backend/gnuplot.h#L76
If you need the image for a publication or something, this should at least enable you to remove the colorbar manually if you want.

**Comment by hiddefolkertsma** [comment]
Again, thanks for the quick reply. Unfortunately removing it manually is not an option because I am using the scatterplot as a frame of a video of a simulation like below:

![video](https://user-images.githubusercontent.com/14166902/93718818-c4893980-fb7e-11ea-848e-1f494af1dafa.gif)

I've managed to circumvent the issue by doing multiple scatter plots, as you suggested. Thanks!

**Comment by alandefreitas** [comment]
That looks really cool. You're saving the images iteratively to later create the video, right? 
If you get to a situation where you can't create multiple scatter plots, maybe you can also crop the images for now.
In any case, I'm trying to give you some options for now but I will look into your issue in the next days.

**Comment by hiddefolkertsma** [comment]
Exactly, the frames are later stitched together with a Python script. Thanks for looking into it. No rush :slightly_smiling_face:

**Comment by alandefreitas** [comment]
Hi @hiddefolkertsma 
This commit 5067ee922170192ee423098dfd571da1e6f937cd should have fixed it.
There's also a new example in [`examples/data_distribution/scatter3/scatter3_7.cpp`](https://github.com/alandefreitas/matplotplusplus/blob/master/examples/data_distribution/scatter3/scatter3_7.cpp).
Thanks for reporting the problem.
