### ISSUE TITLE
undefined variable warning when using legend

### ISSUE THREAD

**Issue by Lehdari** [alandefreitas/matplotplusplus#70]
**Bug category**

- [ ] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [X] *bug - runtime warning*
- [ ] *bug - logic error*

**Describe the bug**
I tried to use legend as shown in here:
https://github.com/alandefreitas/matplotplusplus/blob/master/examples/appearance/labels/legend/legend_5.cpp
But in runtime, I receive a warning stating `line 3078: undefined variable: keyentry` and the plot is unable to render.
I'm using Ubuntu 18.04 and gnuplot 5.2 patchlevel 2 backend.

**Steps to Reproduce**

My exact code:
```
auto y1Plot = matplot::plot(x, y1);
matplot::legend({y1Plot}, {"KDE 1"});
matplot::show();
```

Where x and y1 are of type `std::vector<double>`.

**Environment Details:**
 - OS: Ubuntu 
 - OS Version: 18.04
 - Compiler: GCC
 - Compiler version: 8.4.0

**Comment by alandefreitas** [comment]
Hi @Lehdari, 

You need Gnuplot 5.2.6+ to use legends. 

The `keyentry` command wasn't defined before.

**Comment by alandefreitas** [comment]
Commit 1d33e0b06545fcd99d7cc12d25fcaf3f106ae838 should improve version checking, which is all we can do without throwing an error.
