### ISSUE TITLE
Decrease minimum required CMake version

### ISSUE THREAD

**Issue by acxz** [alandefreitas/matplotplusplus#87]
**Feature category**
- [x] *enhancement - build system*
- [ ] *enhancement - backends*
- [ ] *enhancement - documentation*
- [ ] *enhancement - plot categories*

**The problem**

While building for Ubuntu 18 works, users need to manually install their cmake versions to get things to build. As well as the default gcc version does not support fully c++17, in particular std::filesystem does not exist but instead there is std::experimental::filesystem.

Essentially my issue is that I would like to use matplotplusplus with the default versions of the dependencies available on Ubuntu 18.

**The solution I'd like**
Decrease the minimum cmake required version to 3.10 and allow the building with a slightly older gcc (gcc 7.5).

**Alternatives I've considered**
To get things working on older distributions where the gcc version is not 8 and the cmake version is not 3.14 there is not much that can be done, besides upgrading your distribution like going from Ubuntu 18 to Ubuntu 20 or manually installing new versions of these deps as already recommended.

**Additional context**

Related: https://github.com/alandefreitas/matplotplusplus/pull/59

**Comment by alandefreitas** [comment]
Yes. There's a PR about that: https://github.com/alandefreitas/matplotplusplus/pull/59
I think most things in that PR ended up later in the master branch already so it shouldn't be far from working on GCC7.
As in the comments in https://github.com/alandefreitas/matplotplusplus/pull/59 , we just can't make this a promise for all future releases.
